// AUTO-GENERATED by market/generate_market_data_js.py
// Generated: 2026-02-08T11:25:54.771647
window.UI_GLM_BREADTH_HISTORY = {"asof": "2026-02-08", "days": 1, "series": [{"d": "2026-02-08", "adv": 0, "dec": 15, "unch": 0, "total": 15, "net_ad": -15, "ad_line": -15, "mcc": 0}], "summary": {"pct_ma20": null, "percentile_ma20": null, "vs_1w": null, "vs_1m": null}};
