// AUTO-GENERATED by UI GLM/tools/build_public_data.js
// Source: full_data.js
const FULL_DATA = {
  "overview": {
    "title": "📊 BÁO CÁO TỔNG HỢP THỊ TRƯỜNG",
    "sections": [
      {
        "icon": "📊",
        "title": "`TỔNG QUAN THỊ TRƯỜNG`",
        "content": "<div class='info-box'><p>Thị trường chứng khoán Việt Nam trải qua phiên giảm điểm mạnh với toàn bộ 15 mã trong rổ theo dõi đều chìm trong sắc đỏ, không có mã nào tăng hay đứng giá. VNINDEX mất 1.12% xuống 1,760 điểm trong khi VN30 giảm sâu hơn 1.52% về 1,940 điểm, phản ánh áp lực bán mạnh tập trung vào nhóm bluechips. Điểm đáng lo ngại là độ rộng thị trường hoàn toàn tiêu cực với tỷ lệ volume tăng/giảm ở mức 0, cho thấy dòng tiền đang rút lui toàn diện khỏi thị trường. VNMIDCAP và VNCOND là hai chỉ số chịu thiệt hại nặng nề nhất với mức giảm lần lượt 3.03% và 3.38%, phản ánh tâm lý nhà đầu tư đang cực kỳ thận trọng với các cổ phiếu vốn hóa trung bình và nhóm tiêu dùng tùy chọn.</p></div>"
      },
      {
        "icon": "🔗",
        "title": "`PHÂN TÍCH MỐI QUAN HỆ`",
        "content": "<div class='info-box'><p>Sự phân hóa rõ rệt giữa các chỉ số cho thấy dòng tiền đang rút khỏi các nhóm cổ phiếu rủi ro cao. VN100 giảm 1.64% mạnh hơn VNINDEX cho thấy nhóm Large-cap chịu áp lực bán lớn hơn thị trường chung, trong khi VNMIDCAP mất 3.03% phản ánh tâm lý bán tháo ở phân khúc Mid-cap. Sự chênh lệch giữa VN30 (-1.52%) và VNINDEX (-1.12%) cho thấy bluechips đang dẫn dắt đà giảm, một tín hiệu tiêu cực về tâm lý thị trường. VNSML giảm 1.89% cho thấy cả nhóm Small-cap cũng không được ưa chuộng, xác nhận xu hướng risk-off đang chi phối toàn thị trường.</p></div>"
      },
      {
        "icon": "💰",
        "title": "`DÒNG TIỀN & XU HƯỚNG`",
        "content": "<div class='info-box'><p>Dòng tiền đang thoái lui ở mức báo động với tỷ lệ volume tăng/giảm ở mức 0, phản ánh hoàn toàn không có sự tham gia của phe mua. Áp lực bán mạnh lan rộng khắp thị trường khi tất cả 15 chỉ số đều giảm điểm, cho thấy đây là một đợt bán tháo có tính chất hệ thống hơn là điều chỉnh cục bộ. Xu hướng ngắn hạn đang rất yếu khi toàn bộ các chỉ số chính đều giao dịch dưới MA20, ngoại trừ hai chỉ số VNHEAL và VNENE. Việc không có chỉ số nào giữ vững được mức tăng trong phiên cho thấy tâm lý thị trường đang trong trạng thái bi quan sâu sắc.</p></div>"
      },
      {
        "icon": "🧩",
        "title": "`HỘI TỤ KỸ THUẬT`",
        "content": "<div class='info-box'><p>Các chỉ số chính đều rơi vào vùng quá bán với RSI14 thấp đáng lo ngại. VN30 có RSI 33.25 và VN100 ở mức 33.67 đang tiệm cận vùng oversold, tạo tiền đề cho một nhịp hồi phục kỹ thuật ngắn hạn. VNINDEX với RSI 37.5 cũng đang ở vùng yếu, còn VNFINSELECT và VNFIN cùng có RSI 38.22 cho thấy áp lực bán mạnh ở nhóm tài chính. Tuy nhiên, hai ngoại lệ đáng chú ý là VNHEAL (RSI 67.78) và VNENE (RSI 67.7) đang ở vùng overbought nhưng vẫn giảm điểm nhẹ, có thể là tín hiệu điều chỉnh sau đợt tăng mạnh trước đó. Sự phân kỳ giữa RSI cao và giá giảm ở hai ngành này cần theo dõi thêm để xác nhận xu hướng.</p></div>"
      },
      {
        "icon": "🏆",
        "title": "`XẾP HẠNG`",
        "content": "<div class='info-box'><p>Xếp hạng theo độ mạnh tương đối (kết hợp RSI và mức giảm):</p>\n                <ul>\n                <li>Nhóm dẫn dắt: VNHEAL (RSI 67.78, -0.4%) và VNENE (RSI 67.7, -1.19%) là hai ngành chống đỡ tốt nhất</li>\n                <li>Nhóm trung lập: VNCOND (RSI 49.45), VNMAT (RSI 48.01), VNCONS (RSI 47.38) đang ở vùng trung tính</li>\n                <li>Nhóm yếu nhất: VN30 (RSI 33.25, -1.52%), VN100 (RSI 33.67, -1.64%), VNREAL (RSI 35.28, -0.45%)</li>\n                </ul>\n                <p>VNMIDCAP và VNCOND là hai chỉ số kém hiệu suất nhất cả về giá lẫn momentum, trong khi các chỉ số vốn hóa lớn đều rơi vào vùng quá bán sâu.</p></div>"
      },
      {
        "icon": "🏭",
        "title": "`PHÂN TÍCH NGÀNH`",
        "content": "<div class='info-box'><p>Ngành Y tế (VNHEAL) nổi bật là điểm sáng duy nhất với mức giảm chỉ 0.4% và RSI 67.78, vẫn duy trì vị thế trên MA20, cho thấy tính chất phòng thủ tốt trong bối cảnh thị trường bất ổn. Năng lượng (VNENE) cũng thể hiện độ bền tương đối với RSI 67.7 và giảm 1.19%, vẫn giữ được xu hướng tăng trung hạn. Ngược lại, nhóm Tiêu dùng tùy chọn (VNCOND) và Nguyên vật liệu (VNMAT) chịu áp lực lớn nhất với mức giảm 3.38% và 2.69%, phản ánh lo ngại về tăng trưởng kinh tế. Nhóm Tài chính (VNFIN) giảm 1.66% với RSI 38.22 cho thấy khu vực ngân hàng đang gặp khó khăn, ảnh hưởng tiêu cực đến toàn bộ thị trường. Bất động sản (VNREAL) tuy giảm nhẹ 0.45% nhưng RSI chỉ 35.28 cho thấy xu hướng yếu kéo dài.</p></div>"
      },
      {
        "icon": "📝",
        "title": "`NHẬN ĐỊNH`",
        "content": "<div class='info-box'><p>Thị trường đang trong trạng thái giảm điểm mạnh với độ rộng cực kỳ tiêu cực và dòng tiền thoái lui toàn diện. Tín hiệu tích cực duy nhất là các chỉ số chính đã rơi vào vùng quá bán sâu, tạo tiền đề cho nhịp hồi phục kỹ thuật ngắn hạn trong các phiên tới. Tuy nhiên, việc toàn bộ chỉ số giao dịch dưới MA20 cho thấy xu hướng trung hạn vẫn là giảm và cần thời gian để phục hồi niềm tin. Nhà đầu tư nên ưu tiên các ngành phòng thủ như Y tế và Năng lượng, đồng thời thận trọng với nhóm Tiêu dùng tùy chọn và Mid-cap đang chịu áp lực mạnh. Chiến lược hợp lý là chờ đợi tín hiệu đảo chiều rõ ràng hơn với sự cải thiện về breadth và volume trước khi tham gia mua vào.</p></div>"
      }
    ]
  },
  "vnindex": {
    "title": "VNINDEX - PHÂN TÍCH ĐẦY ĐỦ 100%",
    "sections": [
      {
        "icon": "📈",
        "title": "`XU HƯỚNG GIÁ`",
        "content": "<div class='info-box'><p>VNINDEX đang trong xu hướng giảm rõ ràng khi chỉ số hiện ở mức 1760 điểm, thấp hơn tất cả các đường trung bình động ngắn và trung hạn quan trọng. Giá đóng cửa thấp hơn MA5 (1790), MA10 (1806), MA20 (1845) và cả MA50 (1782.4), cho thấy áp lực bán đang chiếm ưu thế. Hệ thống MA cho thấy sự sắp xếp bearish với MA ngắn hạn cắt xuống MA dài hạn, xác nhận động lực giảm đang mạnh mẽ. Chỉ số đã giảm 140 điểm từ đỉnh 1900 trong tháng 1, tương đương mức điều chỉnh 7.4%. Chỉ có MA200 (1588.7) vẫn đang hỗ trợ ở dưới xa, cho thấy xu hướng dài hạn vẫn còn tích cực nhưng đang bị thử thách nghiêm trọng.</p></div>"
      },
      {
        "icon": "📊",
        "title": "`XU HƯỚNG KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Khối lượng giao dịch ngày 06/02 tăng vượt trội lên 1.133 tỷ, cao hơn đáng kể so với MA20 volume (978 triệu), cho thấy áp lực bán tăng mạnh trong phiên giảm sâu. Đây là tín hiệu tiêu cực khi volume tăng kèm theo giá giảm mạnh 1.12%, phản ánh sự thoái lui của dòng tiền và tâm lý hoảng loạn. OBV ở mức 44.7 tỷ cho thấy dòng tiền lũy kế vẫn dương nhưng có dấu hiệu suy yếu trong các phiên gần đây. So với các phiên đầu tháng 1 khi volume trung bình trên 1.200 tỷ, khối lượng giao dịch gần đây có xu hướng giảm dần, ngoại trừ đợt bán tháo ngày 06/02. Sự phân kỳ giữa giá giảm và volume tăng trong phiên cuối là cảnh báo về lực bán mạnh từ nhà đầu tư.</p></div>"
      },
      {
        "icon": "💹",
        "title": "`KẾT HỢP XU HƯỚNG GIÁ VÀ KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Sự kết hợp giữa giá giảm và khối lượng tăng mạnh trong phiên 06/02 xác nhận đợt bán tháo có tính chất thanh lý và tâm lý bi quan đang lan rộng. Xu hướng giảm giá đi kèm volume cao hơn trung bình cho thấy áp lực bán là thực chất, không phải điều chỉnh kỹ thuật đơn thuần. Trong 20 phiên gần nhất, thị trường liên tục mất điểm từ đỉnh 1900 xuống 1760 với volume trung bình ở mức cao, phản ánh dòng tiền đang rút khỏi thị trường. Mối tương quan âm mạnh giữa price action và volume pattern cho thấy xu hướng giảm hiện tại được xác nhận bởi hành động bán của số đông. Không có dấu hiệu divergence tích cực nào giữa giá và volume để kỳ vọng đảo chiều ngắn hạn.</p></div>"
      },
      {
        "icon": "⚖️",
        "title": "`CUNG-CẦU`",
        "content": "<div class='info-box'><p>Cung đang vượt trội cầu một cách rõ rệt khi chỉ số liên tục phá vỡ các vùng hỗ trợ mà không có phản ứng mua vào mạnh mẽ. Giá đóng cửa tại 1760 điểm, sát biên dưới Bollinger Band (1756.38), cho thấy áp lực bán đã đẩy thị trường về vùng oversold kỹ thuật. Tuy nhiên, việc không có sự phục hồi sau khi chạm vùng này phản ánh tâm lý e dè và thiếu vắng lực cầu hấp thụ. Volume tăng cao trong phiên giảm cho thấy nhiều nhà đầu tư đang chấp nhận cắt lỗ hoặc chốt lời, tạo áp lực cung dư thừa. Spread giữa Upper và Lower Bollinger Band ở mức 177 điểm phản ánh biến động cao và sự mất cân bằng cung cầu nghiêm trọng. Việc RSI chỉ ở mức 37.5 chứng tỏ phe bán đang kiểm soát thị trường nhưng chưa đến mức quá bán cực đoan.</p></div>"
      },
      {
        "icon": "🎯",
        "title": "`MỨC GIÁ QUAN TRỌNG`",
        "content": "<div class='info-box'><p>Kháng cự gần nhất nằm tại MA50 (1782.4), tiếp theo là MA5 (1790) và vùng tâm lý 1800 điểm. Kháng cự mạnh hơn là MA10 (1806) và đặc biệt là MA20 (1845), đây là ngưỡng quan trọng quyết định xu hướng trung hạn. Vùng 1850-1870 là khu vực kháng cự dày đặc từ các đỉnh trước đó trong tháng 1. Hỗ trợ tức thời nằm tại Lower Bollinger Band (1756.38), sau đó là vùng tâm lý 1750 điểm. Hỗ trợ quan trọng tiếp theo là 1730-1740, tương ứng với các đáy trước đó. Nếu mất mốc này, hỗ trợ tiếp theo sẽ là 1700 điểm, một ngưỡng tâm lý quan trọng. Hỗ trợ xa nhất và mạnh nhất là MA200 (1588.7), đại diện cho xu hướng tăng dài hạn từ các năm trước.</p></div>"
      },
      {
        "icon": "📉",
        "title": "`BIẾN ĐỘNG GIÁ`",
        "content": "<div class='info-box'><p>Volatility 20 ngày ở mức 0.94% cho thấy biến động đã tăng lên so với giai đoạn ổn định trước đó, phản ánh sự bất ổn trong tâm lý nhà đầu tư. Bollinger Bands đang mở rộng với khoảng cách Upper-Lower lên đến 177 điểm, xác nhận thị trường đang trong giai đoạn biến động cao. Giá hiện nằm sát biên dưới BB, cho thấy momentum giảm rất mạnh và có thể đã đạt trạng thái oversold ngắn hạn. Daily return âm 1.12% trong phiên 06/02 là mức giảm đáng kể, phản ánh áp lực bán tập trung. Trading range trong 20 phiên qua dao động từ 1760 đến 1900, tạo biên độ 140 điểm (7.4%), cao hơn mức biến động bình thường. Sự mở rộng của Bollinger Bands cảnh báo xu hướng giảm có thể tiếp diễn trước khi có sự ổn định.</p></div>"
      },
      {
        "icon": "🕯️",
        "title": "`MÔ HÌNH GIÁ - MÔ HÌNH NẾN`",
        "content": "<div class='info-box'><p>Phiên 06/02 tạo nến giảm mạnh với thân nến lớn, cho thấy áp lực bán áp đảo trong suốt phiên giao dịch. Chuỗi nến trong 10 phiên gần nhất cho thấy mô hình downtrend rõ ràng với các lower lows và lower highs liên tiếp. Không có dấu hiệu hình thành mô hình đảo chiều tích cực như hammer hay bullish engulfing. Thay vào đó, chuỗi nến giảm dần từ 1900 xuống 1760 tạo thành một kênh giảm ổn định. Việc giá phá vỡ các vùng hỗ trợ 1800 và 1780 mà không có phản ứng phục hồi cho thấy xu hướng giảm còn chưa kết thúc. Cần quan sát các mô hình nến đảo chiều như doji, hammer hoặc bullish engulfing với volume cao để xác nhận điểm đảo chiều tiềm năng. Hiện tại, price action vẫn đang trong kiểm soát của phe bán.</p></div>"
      },
      {
        "icon": "👥",
        "title": "`MARKET BREADTH & TÂM LÝ THỊ TRƯỜNG`",
        "content": "<div class='info-box'><p>Tâm lý thị trường đang ở trạng thái bi quan với RSI(14) chỉ còn 37.5, tiến gần vùng oversold nhưng chưa đủ để kích hoạt phản ứng mua vào mạnh. ADX ở mức 26.96 cho thấy xu hướng giảm hiện tại có độ mạnh trung bình-khá, chưa phải cực mạnh nhưng đủ để duy trì áp lực giảm. Việc cả 4 đường MA ngắn và trung hạn đều nằm trên giá cho thấy độ rộng thị trường yếu với đa số cổ phiếu trong rổ VN-Index đang trong xu hướng giảm. MACD histogram âm sâu tại -15.4 và đường MACD (-3.15) xa dưới signal line (12.25) phản ánh momentum giảm đang rất mạnh. Sentiment tiêu cực được củng cố bởi việc giá liên tục tạo đáy mới trong 2 tuần qua. Không có dấu hiệu capitulation hay exhaustion selling để kỳ vọng đáy gần, thị trường vẫn trong giai đoạn tìm kiếm vùng cân bằng mới.</p></div>"
      },
      {
        "icon": "📜",
        "title": "`LỊCH SỬ & XU HƯỚNG BREADTH`",
        "content": "<div class='info-box'><p>So sánh với lịch sử 20 phiên, breadth thị trường đã suy yếu đáng kể từ đầu tháng 1 khi VN-Index ở đỉnh 1900 điểm. Giai đoạn từ 12/01 đến 19/01, thị trường có breadth tốt với giá dao động quanh 1880-1900 và volume duy trì trên 1 tỷ cổ phiếu mỗi phiên. Từ 26/01, breadth bắt đầu xấu đi với chuỗi giảm liên tiếp, cho thấy số lượng cổ phiếu tăng giá giảm mạnh trong rổ VN-Index. Xu hướng breadth hiện tại là tiêu cực với đa số cổ phiếu giao dịch dưới các đường MA của chúng. OBV tuy vẫn dương nhưng đã không tạo đỉnh mới cùng giá, cho thấy sự phân kỳ tiêu cực về dòng tiền lũy kế. Việc volume tăng trong các phiên giảm và giảm trong các phiên tăng nhẹ phản ánh breadth đang deteriorating. Nếu xu hướng này tiếp diễn, thị trường có thể test các vùng hỗ trợ thấp hơn trước khi có sự cải thiện breadth thực sự.</p></div>"
      },
      {
        "icon": "⚠️",
        "title": "`RỦI RO`",
        "content": "<div class='info-box'><p>Rủi ro hiện tại ở mức cao với nhiều chỉ báo kỹ thuật cảnh báo xu hướng giảm chưa kết thúc. RSI(14) ở 37.5 cho thấy thị trường đang yếu nhưng chưa oversold cực đoan (dưới 30), do đó vẫn có thể giảm thêm. ADX 26.96 xác nhận xu hướng giảm có độ mạnh đủ để tiếp diễn trong ngắn hạn. Vị trí giá dưới tất cả các MA ngắn và trung hạn tạo áp lực kháng cự dày đặc, khiến khả năng phục hồi bị hạn chế. MACD histogram âm sâu -15.4 cho thấy momentum giảm còn mạnh. Volatility tăng cao (0.94%) cảnh báo biến động giá sẽ còn lớn trong thời gian tới, tăng rủi ro cho cả vị thế long và short. Rủi ro thanh khoản xuất hiện nếu thị trường panic selling, dù volume hiện tại vẫn ở mức chấp nhận được. Rủi ro lớn nhất là phá vỡ hỗ trợ 1750, có thể kích hoạt chuỗi stop-loss và đẩy giá xuống sâu hơn về 1700-1720.</p></div>"
      },
      {
        "icon": "🎯",
        "title": "`KHUYẾN NGHỊ VỊ THẾ`",
        "content": "<div class='info-box'><p>Khuyến nghị tạm thời giữ vị thế HOLD hoặc UNDERWEIGHT với thị trường chung cho đến khi có tín hiệu đảo chiều rõ ràng. Nhà đầu tư nên giảm tỷ trọng cổ phiếu xuống 30-40% danh mục, giữ 60-70% tiền mặt để chờ cơ hội mua vào khi có xác nhận đáy. Đối với nhà đầu tư ngắn hạn có kinh nghiệm, có thể xem xét vị thế SHORT nhẹ với stop-loss chặt chẽ tại 1790-1800 nếu giá phục hồi. Tránh bắt đáy khi các chỉ báo momentum vẫn yếu và xu hướng chưa có dấu hiệu đảo chiều. Chỉ xem xét tăng tỷ trọng LONG khi: (1) RSI tạo đáy trên 30 và bật lên, (2) MACD có dấu hiệu golden cross, (3) giá vượt và giữ</p></div>",
        "alert": true
      }
    ]
  },
  "vn30": {
    "title": "VN30 - PHÂN TÍCH ĐẦY ĐỦ 100%",
    "sections": [
      {
        "icon": "📈",
        "title": "`XU HƯỚNG GIÁ`",
        "content": "<div class='info-box'><p>VN30 đang trong xu hướng giảm rõ rệt khi giá đóng cửa 1940 điểm, thấp hơn tất cả các đường MA ngắn và trung hạn. Chỉ số giảm 1.52% trong phiên, tạo thành chuỗi 5 phiên giảm liên tiếp từ mức 2030 xuống 1940 điểm. Giá hiện nằm dưới MA5 (1980), MA10 (2000), MA20 (2039.5) và MA50 (1999.4), cho thấy áp lực bán ngắn hạn mạnh. Các đường MA ngắn hạn đang có dấu hiệu quay đầu giảm và hội tụ, tạo thành một vùng kháng cự dày ở khu vực 1980-2000 điểm. Chỉ số chỉ còn cao hơn MA200 (1761.65), cho thấy xu hướng dài hạn vẫn tích cực nhưng đang bị thách thức nghiêm trọng. Độ dốc giảm nhanh của giá cho thấy động lực downtrend khá mạnh trong giai đoạn hiện tại.</p></div>"
      },
      {
        "icon": "📊",
        "title": "`XU HƯỚNG KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Khối lượng giao dịch tăng đột biến trong phiên với 529 triệu đơn vị, vượt trội so với MA20 (439.7 triệu), cho thấy lực bán gia tăng đáng kể. OBV đạt 15.63 tỷ, nhưng cần theo dõi xu hướng của chỉ báo này trong các phiên tới để xác nhận dòng tiền thực sự. Khối lượng trong 5 phiên giảm gần đây dao động không đều, với các phiên 04/02 và 06/02 có khối lượng cao (469 và 529 triệu), phản ánh panic selling. So với giai đoạn đầu tháng 1 khi VN30 còn ở vùng 2080-2090, khối lượng trung bình thấp hơn, cho thấy dòng tiền đang dè chừng. Sự kết hợp giữa giá giảm mạnh và khối lượng tăng cao là tín hiệu tiêu cực, xác nhận áp lực bán từ nhà đầu tư.</p></div>"
      },
      {
        "icon": "💹",
        "title": "`KẾT HỢP XU HƯỚNG GIÁ VÀ KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Sự kết hợp giữa giá giảm liên tiếp và khối lượng tăng cao trong phiên 06/02 xác nhận xu hướng giảm đang được hỗ trợ bởi dòng tiền bán mạnh. Đây là mô hình price-volume điển hình của giai đoạn distribution và panic selling. Trong các phiên từ 26/01 đến nay, mỗi đợt giảm giá đều đi kèm với khối lượng tương đối cao, cho thấy không phải là giảm giá kỹ thuật đơn thuần. Việc chỉ số phá vỡ liên tiếp các mức hỗ trợ 2000, 1990, 1970 với thanh khoản gia tăng cho thấy tâm lý thị trường đang bi quan. OBV cần được theo dõi để xác định xem dòng tiền có thực sự rút ra hay chỉ là sự phân phối lại tài sản.</p></div>"
      },
      {
        "icon": "⚖️",
        "title": "`CUNG-CẦU`",
        "content": "<div class='info-box'><p>Cung đang áp đảo cầu một cách rõ rệt trong giai đoạn hiện tại, thể hiện qua chuỗi giảm điểm liên tiếp và khối lượng bán tăng cao. Áp lực bán mạnh xuất phát từ cả nhà đầu tư cá nhân lẫn tổ chức khi thị trường lo ngại về các yếu tố vĩ mô. Việc giá liên tục phá các mức hỗ trợ mà không có phản ứng phục hồi cho thấy lực cầu rất yếu ở các mức giá hiện tại. Khối lượng tăng trong phiên giảm điểm phản ánh nhiều lệnh cắt lỗ được kích hoạt, tạo áp lực dồn dập. Dữ liệu không có thông tin về giao dịch khối ngoại, nhưng với quy mô điều chỉnh này, có khả năng dòng vốn ngoại cũng đang rút bớt khỏi nhóm VN30. Vùng 1940-1950 sẽ là khu vực kiểm tra lực cầu hấp thụ của thị trường.</p></div>"
      },
      {
        "icon": "🎯",
        "title": "`MỨC GIÁ QUAN TRỌNG`",
        "content": "<div class='info-box'><p>Kháng cự gần nhất là vùng 1970-1980 (MA5), tiếp theo là 2000 điểm (MA10 và mức tâm lý quan trọng). Kháng cự mạnh hơn nằm ở 2039.5 (MA20 và Bollinger Middle) và 2050-2080 (vùng giá consolidation trước đó). Hỗ trợ tức thời là Bollinger Lower ở 1948, hiện đang bị test, tiếp theo là vùng 1920-1930. Hỗ trợ quan trọng tiếp theo là vùng 1880-1900, tương ứng với fibonacci retracement và vùng giá tháng 12/2025. Nếu tiếp tục giảm sâu, hỗ trợ dài hạn ở MA200 (1761.65) sẽ là điểm cần bảo vệ để giữ xu hướng tăng dài hạn. Vùng 1950-2000 hiện đang trở thành vùng kháng cự dày đặc với nhiều đường MA hội tụ.</p></div>"
      },
      {
        "icon": "📉",
        "title": "`BIẾN ĐỘNG GIÁ`",
        "content": "<div class='info-box'><p>Biến động 20 ngày ở mức 0.94% cho thấy volatility đang ở mức trung bình, nhưng có xu hướng tăng lên trong các phiên gần đây. Daily return -1.52% trong phiên 06/02 cao hơn mức biến động trung bình, phản ánh panic selling. Bollinger Bands đang mở rộng với khoảng cách từ Upper (2130.92) đến Lower (1948.08) là 182.84 điểm, cho thấy thị trường đang trong giai đoạn dao động mạnh. Giá hiện đang test Bollinger Lower, thường là vùng quá bán trong ngắn hạn, có thể xuất hiện phản ứng kỹ thuật. Biên độ giảm từ đỉnh 2090 xuống 1940 trong vòng 2 tuần là 7.18%, phản ánh tốc độ điều chỉnh nhanh. Nếu volatility tiếp tục tăng, có thể kỳ vọng biên độ dao động hàng ngày sẽ mở rộng hơn nữa.</p></div>"
      },
      {
        "icon": "🕯️",
        "title": "`MÔ HÌNH GIÁ - MÔ HÌNH NẾN`",
        "content": "<div class='info-box'><p>VN30 đang hình thành mô hình downtrend channel với các đỉnh và đáy giảm dần trong 2 tuần qua. Chuỗi 5 phiên giảm liên tiếp tạo thành mô hình Five Black Crows, một tín hiệu bearish mạnh. Phiên 06/02 tạo thành nến giảm mạnh với thân nến dài, phản ánh tâm lý bán tháo. Không có dấu hiệu hình thành các mô hình đảo chiều tích cực như hammer hay bullish engulfing ở vùng giá hiện tại. Việc giá liên tục đóng cửa gần đáy của phiên cho thấy áp lực bán kéo dài đến phút cuối. Nếu phiên tiếp theo xuất hiện nến có bóng dưới dài hoặc doji ở vùng 1920-1940, có thể là dấu hiệu exhaustion của đợt bán. Cần quan sát xem có hình thành mô hình double bottom hay falling wedge để tìm điểm đảo chiều.</p></div>"
      },
      {
        "icon": "👥",
        "title": "`MARKET BREADTH & TÂM LÝ THỊ TRƯỜNG`",
        "content": "<div class='info-box'><p>Tâm lý thị trường đang trong trạng thái bi quan và sợ hãi với RSI(14) chỉ còn 33.25, tiến gần vùng quá bán. Với đặc thù của VN30 gồm 30 cổ phiếu vốn hóa lớn nhất, việc chỉ số giảm mạnh cho thấy phần lớn blue-chips đang chịu áp lực bán. Market breadth có khả năng nghiêng về phía giảm giá với số lượng cổ phiếu giảm áp đảo số lượng tăng trong rổ VN30. Tâm lý panic thể hiện qua khối lượng bán tăng cao và việc giá phá nhiều mức hỗ trợ liên tiếp. Các nhà đầu tư đang có xu hướng risk-off, bán tháo cổ phiếu large-cap để chốt lời hoặc cắt lỗ. Sự suy yếu của VN30 thường kéo theo toàn bộ thị trường do hiệu ứng tâm lý và tính thanh khoản cao của nhóm này.</p></div>"
      },
      {
        "icon": "📜",
        "title": "`LỊCH SỬ & XU HƯỚNG BREADTH`",
        "content": "<div class='info-box'><p>So với giai đoạn đầu tháng 1 khi VN30 dao động quanh 2080-2090 với market breadth cân bằng hơn, hiện tại breadth đã chuyển sang trạng thái tiêu cực rõ rệt. Xu hướng giảm từ 26/01 cho thấy breadth xấu đi dần với ngày càng nhiều cổ phiếu trong rổ VN30 không thể duy trì được giá. Lịch sử cho thấy khi VN30 điều chỉnh 7-8% trong thời gian ngắn, thường đi kèm với deteriorating breadth nghiêm trọng. Giai đoạn tích cực cuối năm 2025 với giá vượt xa MA200 đã tạo nền tảng, nhưng breadth hiện tại đang cho thấy sự phân kỳ tiêu cực. Nếu trong vài phiên tới xuất hiện dấu hiệu divergence tích cực với một số cổ phiếu trong VN30 bắt đầu hồi phục trong khi chỉ số vẫn giảm, đó có thể là tín hiệu sớm của đảo chiều.</p></div>"
      },
      {
        "icon": "⚠️",
        "title": "`RỦI RO`",
        "content": "<div class='info-box'><p>Rủi ro hiện tại ở mức cao với nhiều tín hiệu cảnh báo hội tụ. RSI(14) ở 33.25 cho thấy thị trường đang oversold nhưng chưa đủ sâu để tạo đáy vững chắc. ADX(14) ở 41.04 cho thấy xu hướng giảm đang rất mạnh và có thể tiếp tục. MACD histogram âm sâu -15.45 với MACD line (-11.12) xa dưới Signal line (4.33), xác nhận momentum giảm mạnh. Volatility tăng cao làm tăng rủi ro cho các vị thế giao dịch. Giá đang test Bollinger Lower, nếu thủng sẽ mở rộng không gian giảm thêm. Rủi ro tâm lý khi nhà đầu tư có thể tiếp tục bán tháo nếu không thấy tín hiệu ổn định. Rủi ro thanh khoản tăng khi thị trường panic, spread có thể mở rộng. Với vị thế hiện tại, rủi ro downside cao hơn rõ rệt so với upside potential trong ngắn hạn.</p></div>"
      },
      {
        "icon": "🎯",
        "title": "`KHUYẾN NGHỊ VỊ THẾ`",
        "content": "<div class='info-box'><p>Khuyến nghị giữ vị thế HOLD hoặc giảm tỷ trọng với nhóm VN30 trong ngắn hạn. Với các tín hiệu kỹ thuật tiêu cực hội tụ, việc long mới ở thời điểm này có rủi ro cao. Nhà đầu tư đang nắm giữ nên cân nhắc cắt lỗ nếu giá thủng 1930 hoặc giảm tỷ trọng xuống 30-40% danh mục. Trader ngắn hạn có thể xem xét short position nhưng cần đặt stoploss chặt ở 1970-1980 do RSI đang gần vùng quá bán. Nhà đầu tư dài hạn có thể chờ tín hiệu rõ ràng hơn về việc hình thành đáy, ví dụ như RSI dưới 30 kết hợp với bullish divergence. Khuyến nghị chờ đợi các dấu hiệu đảo chiều rõ ràng như: giá vượt lại MA5, RSI tăng trên 40, hoặc MACD crossover tích cực trước khi tăng tỷ trọng. Ưu tiên bảo toàn vốn trong giai đoạn biến động cao này.</p></div>",
        "alert": true
      },
      {
        "icon": "🎯",
        "title": "`GIÁ MỤC TIÊU`",
        "content": "<div class='info-box'><p>Trong kịch bản giảm tiếp, mục tiêu hạ ngắn hạn là vùng 1920-1930, tiếp theo là 1880-1900 nếu áp lực bán tiếp diễn. Support mạnh hơn ở vùng 1850 tương ứng với các đáy trước đó. Trong kịch bản phục hồi, mục tiêu tăng đầu tiên là 1970-1980 (MA</p></div>"
      }
    ]
  },
  "vn100": {
    "title": "VN100 - PHÂN TÍCH ĐẦY ĐỦ 100%",
    "sections": [
      {
        "icon": "📈",
        "title": "`XU HƯỚNG GIÁ`",
        "content": "<div class='info-box'><p>VN100 đang trong xu hướng giảm rõ rệt khi giao dịch dưới tất cả các đường trung bình động ngắn và trung hạn quan trọng. Giá đóng cửa 1817.49 thấp hơn MA5 (1853.66), MA10 (1871.74), MA20 (1915.3) và MA50 (1886.83), cho thấy áp lực bán đang chiếm ưu thế mạnh mẽ. Chỉ số đã giảm 1.64% trong phiên và giảm gần 8% so với đỉnh gần nhất vào giữa tháng 1/2026. Chuỗi các đường MA ngắn hạn đang sắp xếp theo xu hướng giảm với MA5 < MA10 < MA20, xác nhận động lực xuống mạnh. Điểm tích cực duy nhất là giá vẫn duy trì trên MA200 (1695.18), cho thấy xu hướng dài hạn chưa bị phá vỡ hoàn toàn. Khoảng cách giá hiện tại so với MA20 đã lên tới gần 5%, phản ánh tình trạng oversold ngắn hạn.</p></div>"
      },
      {
        "icon": "📊",
        "title": "`XU HƯỚNG KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Khối lượng giao dịch trong phiên 2026-02-06 đạt 885.46 triệu, cao hơn đáng kể so với trung bình 20 phiên (817.84 triệu), tăng khoảng 8.3%. Sự gia tăng khối lượng đi kèm với phiên giảm mạnh cho thấy áp lực bán tháo đang tăng cao và nhà đầu tư đang tích cực chốt lời hoặc cắt lỗ. Chỉ báo OBV ở mức 36.95 tỷ cho thấy dòng tiền tích lũy vẫn ở mức khá, nhưng cần theo dõi xu hướng giảm của OBV trong các phiên tới để xác nhận dòng tiền rút lui. Khối lượng trong giai đoạn giảm từ giữa tháng 1 đến nay có xu hướng tăng dần, đặc biệt tăng mạnh trong các phiên đầu tháng 2. Điều này phản ánh sự lo ngại và hoảng loạn của thị trường khi giá phá vỡ các ngưỡng hỗ trợ quan trọng.</p></div>"
      },
      {
        "icon": "💹",
        "title": "`KẾT HỢP XU HƯỚNG GIÁ VÀ KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Sự kết hợp giữa giá giảm mạnh và khối lượng tăng cao là tín hiệu cảnh báo tiêu cực, xác nhận áp lực bán đang rất lớn. Đây là đặc điểm của một đợt bán tháo có conviction cao, không phải chỉ là điều chỉnh kỹ thuật thông thường. Trong 5 phiên giao dịch gần nhất, mỗi khi giá giảm đều đi kèm khối lượng cao hơn trung bình, cho thấy dòng tiền đang rút khỏi thị trường. Các phiên phục hồi nhẹ (như ngày 29/1 và 30/1) đều có khối lượng thấp, phản ánh sự yếu ớt của lực cầu. Xu hướng price-volume hiện tại cho thấy thị trường đang trong giai đoạn distribution (phân phối), khi những người nắm giữ dài hạn bắt đầu thoát hàng. Cần có tín hiệu khối lượng tăng mạnh kèm giá tăng để xác nhận sự đảo chiều xu hướng.</p></div>"
      },
      {
        "icon": "⚖️",
        "title": "`CUNG-CẦU`",
        "content": "<div class='info-box'><p>Cán cân cung-cầu đang nghiêng hẳn về phía cung với áp lực bán chiếm ưu thế tuyệt đối. Giá đã phá vỡ nhiều mức hỗ trợ quan trọng trong tuần qua mà không có sự phản kháng đáng kể từ phe mua, cho thấy lực cầu đang rất yếu. RSI ở mức 33.67 phản ánh tình trạng bán quá mức ngắn hạn, nhưng chưa đủ thấp để kích hoạt sóng mua đáng kể. Áp lực bán tăng mạnh có thể đến từ việc các nhà đầu tư lo ngại về triển vọng kinh tế hoặc kỹ thuật stop-loss tự động được kích hoạt khi giá phá các mức hỗ trợ. Vùng giá 1815-1820 đang xuất hiện lực mua hỗ trợ nhẹ do tiệm cận đường Bollinger Lower và tâm lý oversold, nhưng chưa đủ mạnh để đảo chiều xu hướng. Nếu không có thông tin tích cực hoặc sự can thiệp, cung sẽ tiếp tục áp đảo trong ngắn hạn.</p></div>"
      },
      {
        "icon": "🎯",
        "title": "`MỨC GIÁ QUAN TRỌNG`",
        "content": "<div class='info-box'><p>Mức hỗ trợ quan trọng nhất hiện tại là vùng 1817-1820, trùng với đường Bollinger Lower Band (1817.62) và vùng giá thấp nhất của phiên hôm nay. Nếu vùng này bị phá vỡ, hỗ trợ tiếp theo sẽ là 1780-1790, tương ứng với mức Fibonacci retracement 38.2% của đợt tăng trước đó. Hỗ trợ mạnh hơn nằm ở vùng 1720-1750, là vùng congestion quan trọng trong quá khứ. Về kháng cự, mức ngắn hạn đầu tiên là vùng 1850-1860 (gần MA5), tiếp theo là 1870-1880 (vùng MA10). Kháng cự mạnh hơn nằm ở 1895-1900 (đỉnh gần nhất) và đặc biệt là vùng 1915-1920 (MA20 và Bollinger Middle). Đường MA50 tại 1886 cũng sẽ đóng vai trò kháng cự động quan trọng nếu có phục hồi. Mức tâm lý 1800 sẽ là ngưỡng quan trọng cần giữ vững để tránh tâm lý hoảng loạn lan rộng.</p></div>"
      },
      {
        "icon": "📉",
        "title": "`BIẾN ĐỘNG GIÁ`",
        "content": "<div class='info-box'><p>Biến động thị trường đang ở mức cao với volatility 20 ngày đạt 0.99%, phản ánh sự bất ổn và lo ngại của nhà đầu tư. Giá hiện đang giao dịch sát đường Bollinger Lower Band, cho thấy trạng thái oversold ngắn hạn với khả năng xuất hiện nhịp hồi kỹ thuật. Băng thông Bollinger đang mở rộng (khoảng cách Upper-Lower tăng lên 195 điểm), xác nhận xu hướng biến động tăng cao và thị trường đang trong giai đoạn breakout. Daily return -1.64% là mức giảm đáng kể, cao hơn mức biến động trung bình. Range giao dịch trong phiên rộng hơn so với các phiên trước, cho thấy sự phân hóa mạnh về quan điểm giữa người mua và người bán. Biến động cao tạo cơ hội cho trader ngắn hạn nhưng cũng làm tăng rủi ro cho nhà đầu tư dài hạn. Xu hướng mở rộng biến động thường kéo dài 5-10 phiên trước khi ổn định trở lại.</p></div>"
      },
      {
        "icon": "🕯️",
        "title": "`MÔ HÌNH GIÁ - MÔ HÌNH NẾN`",
        "content": "<div class='info-box'><p>Biểu đồ nến trong phiên 2026-02-06 cho thấy một cây nến giảm mạnh với thân nến dài, phản ánh áp lực bán áp đảo suốt phiên giao dịch. Chuỗi 6 phiên giảm liên tiếp từ đỉnh 1976 xuống 1817 tạo thành mô hình \"đường giảm kéo dài\" (extended downtrend), tín hiệu bearish mạnh mẽ. Trong dữ liệu 20 phiên gần nhất, có thể nhận diện mô hình \"double top\" hình thành ở vùng 1975-1960 vào giữa tháng 1, đã được xác nhận khi giá phá vỡ đường neckline tại 1935. Mô hình này thường dự báo mức giảm tương đương với chiều cao của pattern, khoảng 40-50 điểm, tương ứng target 1880-1890 đã hoàn thành. Hiện tại đang hình thành mô hình \"falling knife\" với các nến đỏ liên tiếp không có bóng trên dài, cho thấy không có sự phản kháng từ phe mua. Cần xuất hiện các mô hình đảo chiều như hammer, bullish engulfing hoặc morning star để xác nhận đáy ngắn hạn.</p></div>"
      },
      {
        "icon": "👥",
        "title": "`MARKET BREADTH & TÂM LÝ THỊ TRƯỜNG`",
        "content": "<div class='info-box'><p>Tâm lý thị trường đang rất tiêu cực với tình trạng bán tháo lan rộng trên toàn chỉ số VN100. RSI ở mức 33.67 cho thấy thị trường đang trong vùng oversold nhẹ, phản ánh tâm lý bi quan đang lan tỏa. ADX ở mức 35.48 cho thấy xu hướng giảm đang rất mạnh và rõ ràng, chưa có dấu hiệu suy yếu. Breadth của thị trường có khả năng đang rất yếu với số lượng cổ phiếu giảm giá vượt xa số cổ phiếu tăng trong rổ VN100. Tâm lý nhà đầu tư chuyển từ thận trọng sang lo lắng và có dấu hiệu hoảng loạn khi các mức hỗ trợ kỹ thuật quan trọng bị phá vỡ. Áp lực chốt lời từ những người mua ở vùng đáy tháng 12/2025 và áp lực cắt lỗ từ những người mua đỉnh đang tạo hiệu ứng domino. Sentiment tiêu cực này có thể kéo dài thêm vài phiên cho đến khi xuất hiện oversold thực sự hoặc có thông tin hỗ trợ từ yếu tố vĩ mô.</p></div>"
      },
      {
        "icon": "📜",
        "title": "`LỊCH SỬ & XU HƯỚNG BREADTH`",
        "content": "<div class='info-box'><p>So sánh với các đợt điều chỉnh trước đây, mức độ suy giảm hiện tại của VN100 đang ở mức trung bình đến nặng. Chỉ số đã giảm gần 160 điểm (8%) từ đỉnh trong vòng 15 phiên giao dịch, tốc độ giảm tương đối nhanh. Nhìn vào dữ liệu 20 phiên, breadth đã chuyển từ tích cực sang tiêu cực rõ rệt từ phiên 26/1 khi có phiên giảm sâu đầu tiên. Xu hướng breadth xấu đi liên tục với số lượng ngày giảm (11 phiên) nhiều hơn ngày tăng (9 phiên) trong 20 phiên gần nhất. Đặc biệt, các phiên giảm có mức độ mạnh hơn các phiên tăng, với biên độ giảm trung bình lớn hơn biên độ tăng. Lịch sử cho thấy khi breadth xấu đi kéo dài trên 10 phiên, thị trường thường cần 3-5 phiên để tạo đáy và 10-15 phiên để phục hồi về vùng cân bằng. Xu hướng breadth hiện tại cho thấy thị trường đang trong giai đoạn giữa của đợt điều chỉnh, chưa phải giai đoạn tạo đáy ổn định.</p></div>"
      },
      {
        "icon": "⚠️",
        "title": "`RỦI RO`",
        "content": "<div class='info-box'><p>Rủi ro trong ngắn hạn đang ở mức cao với nhiều tín hiệu cảnh báo đồng thời xuất hiện. RSI 33.67 mặc dù đã vào vùng oversold nhẹ nhưng vẫn chưa đủ thấp để loại trừ khả năng giảm sâu hơn, đặc biệt trong thị trường có xu hướng mạnh. ADX cao (35.48) xác nhận xu hướng giảm đang rất mạnh và khó đảo chiều trong ngắn hạn, tăng rủi ro cho các vị thế long. MACD histogram âm sâu (-14.25) với đường MACD xa dưới đường signal cho thấy momentum giảm chưa có dấu hiệu chững lại. Volatility cao (0.99%) làm tăng rủi ro biến động giá mạnh, có thể gây tổn thất lớn cho các vị thế không có stop-loss. Rủi ro kỹ thuật lớn nhất là khả năng phá vỡ mức 1817 sẽ kích hoạt thêm lệnh stop-loss, tạo áp lực bán dồn dập. Rủi ro tâm lý cũng đáng lo ngại khi thị trường có thể rơi vào panic selling nếu phá ngưỡng 1800. Nhà đầu t</p></div>"
      }
    ]
  },
  "vnmidcap": {
    "title": "VNMIDCAP - PHÂN TÍCH ĐẦY ĐỦ 100%",
    "sections": [
      {
        "icon": "📈",
        "title": "`XU HƯỚNG GIÁ`",
        "content": "<div class='info-box'><p>Chỉ số VNMIDCAP đang trong xu hướng giảm rõ rệt khi giá đóng cửa 2154.2 điểm, giảm mạnh 3.03% trong phiên. Giá hiện nằm dưới tất cả các đường trung bình động quan trọng: MA5 (2222.4), MA10 (2209.72), MA20 (2239.3), MA50 (2237.23) và MA200 (2232.98). Các đường MA ngắn hạn bắt đầu quay đầu giảm và có xu hướng cắt xuống các MA dài hạn, tạo tín hiệu downtrend. Giá đã phá vỡ vùng hỗ trợ 2180-2200 điểm và tiếp tục suy yếu. Khoảng cách giữa giá hiện tại và MA20 đã lên tới 85 điểm, cho thấy áp lực bán đang rất lớn. Đây là phiên giảm mạnh nhất trong chuỗi 20 ngày gần đây, phản ánh tâm lý bi quan đang lan rộng.</p></div>"
      },
      {
        "icon": "📊",
        "title": "`XU HƯỚNG KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Khối lượng giao dịch ngày 06/02 tăng mạnh lên 403.2 triệu đơn vị, cao hơn đáng kể so với trung bình 20 ngày (380.5 triệu). Sự gia tăng khối lượng đi kèm với phiên giảm giá mạnh là dấu hiệu xấu, thể hiện áp lực bán tháo từ nhà đầu tư. OBV ở mức 11.64 tỷ cho thấy dòng tiền đang rời khỏi thị trường trong những phiên gần đây. So với các phiên hồi phục nhẹ trước đó (02-04/02), khối lượng trong những ngày tăng giá thấp hơn rõ rệt, chứng tỏ thiếu sự tham gia của dòng tiền mua vào. Xu hướng phân phối đang chiếm ưu thế khi khối lượng tăng trong các phiên giảm giá.</p></div>"
      },
      {
        "icon": "💹",
        "title": "`KẾT HỢP XU HƯỚNG GIÁ VÀ KHỐI LƯỢNG`",
        "content": "<div class='info-box'><p>Sự kết hợp giữa giá giảm mạnh 3.03% và khối lượng tăng vượt trung bình xác nhận xu hướng giảm đang được hỗ trợ bởi lực bán thực sự. Đây không phải là đợt giảm giá kỹ thuật với thanh khoản thấp mà là sự thoái lui có động lực mạnh từ nhà đầu tư. Phân kỳ tiêu cực rõ ràng khi giá liên tục lập đáy thấp hơn trong khi OBV cho thấy dòng tiền tích lũy không đủ mạnh để đảo chiều. Các phiên hồi phục nhẹ từ 30/01 đến 04/02 đều có khối lượng yếu, không tạo được nền tảng vững chắc. Mô hình price-volume hiện tại phản ánh giai đoạn distribution và capitulation đang diễn ra.</p></div>"
      },
      {
        "icon": "⚖️",
        "title": "`CUNG-CẦU`",
        "content": "<div class='info-box'><p>Áp lực cung đang áp đảo hoàn toàn với phiên giảm 3.03% cho thấy phe bán kiểm soát thị trường. Lực mua dường như đã cạn kiệt sau những nỗ lực hồi phục thất bại trong tuần trước. Vùng giá 2250-2280 điểm trước đây là hỗ trợ nay đã trở thành kháng cự mạnh khi không còn lực cầu bảo vệ. Khối lượng bán tăng cao cho thấy nhiều nhà đầu tư đang chốt lời hoặc cắt lỗ, tạo nguồn cung dồi dào. Hiện chưa quan sát thấy vùng cầu tích lũy rõ ràng nào ở mức giá hiện tại. Tỷ lệ cung-cầu đang nghiêng về phía cung với tỷ trọng khoảng 70-30, phản ánh tâm lý bi quan đang lan rộng trong nhóm cổ phiếu vốn hóa trung bình.</p></div>"
      },
      {
        "icon": "🎯",
        "title": "`MỨC GIÁ QUAN TRỌNG`",
        "content": "<div class='info-box'><p>Kháng cự gần nhất là đường MA5 tại 2222.4 điểm, tiếp theo là vùng 2240-2260 điểm nơi tập trung MA20, MA50 và MA200. Kháng cự mạnh hơn nằm ở ngưỡng 2280-2300 điểm, là đỉnh cũ và vùng giá tâm lý quan trọng. Hỗ trợ tức thời là Lower Bollinger Band tại 2158.08 điểm, gần sát với giá đóng cửa hiện tại. Hỗ trợ tiếp theo nằm ở vùng 2120-2130 điểm, là đáy của các phiên giảm sâu trước đó tháng 01. Nếu thủng mức này, hỗ trợ xa hơn có thể ở quanh 2080-2100 điểm. Ngưỡng tâm lý 2150 điểm cũng là mốc quan trọng cần theo dõi trong ngắn hạn.</p></div>"
      },
      {
        "icon": "📉",
        "title": "`BIẾN ĐỘNG GIÁ`",
        "content": "<div class='info-box'><p>Volatility 20 ngày ở mức 1.53% cho thấy biến động đang ở mức trung bình, nhưng phiên giảm 3.03% vượt xa ngưỡng này, phản ánh cú sốc giá đột biến. Giá hiện đang test Lower Bollinger Band (2158.08), với băng thông Bollinger khá rộng (162 điểm từ Upper đến Lower), cho thấy thị trường đang trong giai đoạn volatility cao. Giá đã di chuyển từ Middle Band xuống Lower Band chỉ trong vài phiên, thể hiện momentum giảm mạnh. Khi giá chạm hoặc vượt qua Lower Band thường báo hiệu tình trạng oversold ngắn hạn. Tuy nhiên, trong xu hướng giảm mạnh, giá có thể \"đi dọc\" theo Lower Band một thời gian trước khi hồi phục.</p></div>"
      },
      {
        "icon": "🕯️",
        "title": "`MÔ HÌNH GIÁ - MÔ HÌNH NẾN`",
        "content": "<div class='info-box'><p>Phiên 06/02 tạo ra một cây nến đỏ dài với thân nến lớn, thể hiện áp lực bán mạnh trong suốt cả phiên. Chuỗi 3 phiên gần nhất (04-06/02) cho thấy mô hình Evening Star chưa hoàn chỉnh nhưng đã báo hiệu sự đảo chiều từ hồi phục sang giảm. Mô hình giá trong 20 ngày qua cho thấy Lower High và Lower Low liên tiếp, xác nhận downtrend. Đã hình thành mô hình giảm giá Breaking Support khi giá phá vỡ vùng 2180-2200 điểm với khối lượng lớn. Chưa xuất hiện các mô hình đảo chiều tăng như Hammer hay Bullish Engulfing, cho thấy đáy chưa được thiết lập. Nếu phiên tiếp theo tạo lower shadow dài có thể là dấu hiệu exhaustion bán.</p></div>"
      },
      {
        "icon": "👥",
        "title": "`MARKET BREADTH & TÂM LÝ THỊ TRƯỜNG`",
        "content": "<div class='info-box'><p>Với mức giảm 3.03% của chỉ số, có thể suy đoán phần lớn cổ phiếu trong rổ VNMIDCAP đều chịu áp lực bán mạnh. Breadth tiêu cực đang chi phối với tỷ lệ cổ phiếu giảm giá có thể lên tới 70-80% tổng số thành phần. Tâm lý thị trường đang trong trạng thái sợ hãi và hoảng loạn khi RSI(14) chỉ còn 38.96, tiến gần vùng oversold. Không có dấu hiệu divergence tích cực từ breadth indicators, cho thấy sự suy yếu đồng loạt trên diện rộng. Các cổ phiếu vốn hóa trung bình thường nhạy cảm hơn với thanh khoản và tâm lý risk-off, dẫn đến bán tháo mạnh hơn khi thị trường điều chỉnh. Sentiment đang ở mức rất tiêu cực trong ngắn hạn.</p></div>"
      },
      {
        "icon": "📜",
        "title": "`LỊCH SỬ & XU HƯỚNG BREADTH`",
        "content": "<div class='info-box'><p>So với đợt giảm mạnh cuối tháng 01 (từ 2297 xuống 2182 điểm trong 5 phiên), đợt giảm hiện tại có tính chất leo thang cao hơn với phiên giảm 3.03% là mức sụt giảm mạnh nhất. Breadth đã suy yếu dần từ giữa tháng 01 khi chỉ số không thể vượt qua mốc 2300 điểm. Xu hướng breadth từ tích cực (đầu tháng 01) chuyển sang trung tính (giữa tháng) và hiện tại là tiêu cực rõ rệt. Lịch sử cho thấy khi VNMIDCAP có breadth yếu kéo dài trên 7-10 phiên, thường cần thời gian 2-3 tuần để phục hồi hoàn toàn. Đợt bán tháo hiện tại đã bước sang tuần thứ 2, với breadth tiếp tục xấu đi chứ chưa có dấu hiệu đảo chiều.</p></div>"
      },
      {
        "icon": "⚠️",
        "title": "`RỦI RO`",
        "content": "<div class='info-box'><p>Rủi ro hiện tại ở mức cao với nhiều tín hiệu cảnh báo đồng loạt. RSI(14) tại 38.96 đang tiến gần vùng oversold nhưng vẫn còn không gian giảm thêm, chưa đủ điều kiện để đảo chiều. MACD âm sâu (-9.33) và histogram âm tăng (-3.91) cho thấy momentum giảm đang tăng tốc. ADX(14) ở mức 33.56 xác nhận xu hướng giảm có sức mạnh và có thể kéo dài. Giá nằm dưới tất cả các MA chính, tạo rủi ro tiếp tục điều chỉnh sâu hơn. Volatility tăng đột biến trong phiên (3.03% so với trung bình 1.53%) cho thấy thị trường không ổn định. Rủi ro breakout giảm khỏi Lower Bollinger Band là hiện hữu. Nhà đầu tư nắm giữ vị thế long đang chịu drawdown đáng kể và cần có biện pháp quản trị rủi ro chặt chẽ.</p></div>"
      },
      {
        "icon": "🎯",
        "title": "`KHUYẾN NGHỊ VỊ THẾ`",
        "content": "<div class='info-box'><p>Khuyến nghị HOLD hoặc REDUCE đối với vị thế hiện tại, tránh mua mới trong giai đoạn này. Nhà đầu tư nên giảm tỷ trọng về mức 30-40% danh mục nếu đang overweight nhóm midcap, chuyển sang defensive hoặc nắm tiền mặt. Đối với trader ngắn hạn, có thể xem xét SHORT hoặc chờ tín hiệu đảo chiều rõ ràng hơn trước khi vào lệnh. Stop-loss nên được đặt chặt chẽ ở mức 2130 điểm nếu nắm giữ vị thế long. Chỉ cân nhắc mua vào khi có các tín hiệu: RSI xuống dưới 30 và bật lên, MACD histogram chuyển dương, hoặc xuất hiện mô hình nến đảo chiều với khối lượng xác nhận. Ưu tiên chiến lược phòng thủ và bảo toàn vốn trong bối cảnh rủi ro cao như hiện nay.</p></div>",
        "alert": true
      },
      {
        "icon": "🎯",
        "title": "`GIÁ MỤC TIÊU`",
        "content": "<div class='info-box'><p>Trong kịch bản tiêu cực, mục tiêu giảm ngắn hạn là vùng 2120-2130 điểm (hỗ trợ kỹ thuật), và xa hơn là 2080-2100 điểm nếu tâm lý bán tháo tiếp diễn. Trong kịch bản hồi phục, mục tiêu tăng đầu tiên là 2200-2220 điểm (MA5 và vùng kháng cự gần), tiếp theo là 2240-2260 điểm (cụm MA20/50/200). Chỉ khi vượt vững vàng qua 2260 điểm, mục tiêu xa hơn mới là 2300 điểm. Theo Fibonacci retracement từ đỉnh 2297 xuống đáy hiện tại, mức 38.2% retracement nằm quanh 2208 điểm và 50% retracement ở 2225 điểm có thể là các target hồi kỹ thuật. Risk/reward hiện tại không hấp dẫn cho vị thế long, cần chờ giá tìm được vùng đáy ổn định hơn.</p>\n                <p>KỊCH BẢN WHAT-IF</p>\n                <p>Kịch bản tiêu cực (40% khả năng): Chỉ số tiếp tục test và phá vỡ hỗ trợ 2150 điểm, giảm sâu về vùng 2080-2120 điểm trong 3-5 phiên tới</p></div>"
      }
    ]
  }
};
