// AUTO-GENERATED by market/generate_market_data_js.py
// Generated: 2026-02-08T11:25:54.771370
window.UI_GLM_MARKET_BREADTH_SNAPSHOT = {"asof": "2026-02-08", "advancing": 0, "declining": 15, "unchanged": 0, "total_stocks": 15, "net_ad": -15, "source": "index-level (simplified)"};
