// AUTO-GENERATED by market/generate_market_data_js.py
// Generated: 2026-02-12T09:42:50.173178
window.UI_GLM_MARKET_BREADTH_SNAPSHOT = {"asof": "2026-02-12", "advancing": 323, "declining": 261, "unchanged": 166, "total_stocks": 750, "net_ad": 62, "source": "vnstock-repo"};
