// AUTO-GENERATED by UI GLM/tools/auto_daily_update.sh
// This file is updated on each deploy to keep the dashboard header in sync.
window.UI_GLM_REPORT_META = {
  stamp: "",
  asof_iso: "",
  human_date: "--/--/----",
  human_updated_at: "--/--/---- --:--",
  source_docx: ""
};

