// AUTO-GENERATED by GitHub Actions
window.UI_GLM_REPORT_META = {
  stamp: "20260210_100528",
  asof_iso: "2026-02-10",
  human_date: "10/02/2026",
  human_updated_at: "10/02/2026 10:05",
  source_docx: "GitHub Actions Auto"
};
