// AUTO-GENERATED by UI GLM/tools/auto_daily_update.sh
window.UI_GLM_REPORT_META = {
  stamp: "20251229_203042",
  asof_iso: "2025-12-29",
  human_date: "29/12/2025",
  human_updated_at: "29/12/2025 20:30",
  source_docx: "BaoCao_20251229_203042.docx"
};
