"""
Tạo JS data files cho dashboard charts.
Chỉ generate các file có data thật từ index OHLCV + breadth.
"""

import json
import sys
import logging
from datetime import datetime
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

sys.path.insert(0, str(Path(__file__).resolve().parent))

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = PROJECT_ROOT / "market_cache"


def load_json(filename):
    path = CACHE_DIR / filename
    if not path.exists():
        log.warning(f"Not found: {path}")
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def write_js(filename, var_name, data):
    """Ghi JS file: window.VAR_NAME = data;"""
    path = PROJECT_ROOT / filename
    content = f"// AUTO-GENERATED by market/generate_market_data_js.py\n"
    content += f"// Generated: {datetime.now().isoformat()}\n"
    content += f"window.{var_name} = {json.dumps(data, ensure_ascii=False)};\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    log.info(f"Written: {path} ({path.stat().st_size:,} bytes)")


# ============================================================================
# 1. INDEX OHLCV (for TradingView charts)
# ============================================================================

def generate_index_ohlcv():
    """Tạo index_ohlcv.js - data OHLCV cho chart."""
    data = load_json("index_ohlcv.json")
    if not data:
        log.warning("No index_ohlcv.json, skipping")
        return

    output = {
        "asof": data.get("asof", ""),
        "updated_at": datetime.now().isoformat(),
        "indices": {},
    }

    for key, index_data in data.get("indices", {}).items():
        output["indices"][key] = {
            "name": index_data["name"],
            "method": "vnstock-VCI",
            "bars": index_data["bars"],
        }

    write_js("index_ohlcv.js", "UI_GLM_INDEX_OHLCV", output)


# ============================================================================
# 2. MARKET BREADTH SNAPSHOT (enhanced with stock-level data if available)
# ============================================================================

def generate_breadth_snapshot():
    """Tạo market_breadth_snapshot.js - prefer stock-level breadth, fallback to index-level."""
    # Try stock-level breadth first (from TCBS API)
    stock_snapshot = load_json("stock_snapshot.json")
    stock_breadth = stock_snapshot.get("breadth", {}) if stock_snapshot else {}

    if stock_breadth and stock_breadth.get("total_stocks", 0) > 50:
        # Use real stock-level breadth
        breadth = {
            "asof": stock_breadth.get("asof", stock_snapshot.get("asof", "")),
            "universe": "HOSE",
            "advancing": stock_breadth.get("advancing", 0),
            "declining": stock_breadth.get("declining", 0),
            "unchanged": stock_breadth.get("unchanged", 0),
            "total_stocks": stock_breadth.get("total_stocks", 0),
            "advance_volume": stock_breadth.get("advance_volume", 0),
            "decline_volume": stock_breadth.get("decline_volume", 0),
            "total_volume": stock_breadth.get("total_volume", 0),
            "trin": stock_breadth.get("trin"),
            "volume_ratio": stock_breadth.get("volume_ratio"),
            "mcclellan": stock_breadth.get("mcclellan"),
            "mcclellan_type": stock_breadth.get("mcclellan_type", "Net A-D"),
            "source": stock_breadth.get("source", "TCBS"),
        }
        log.info("  Using stock-level breadth data")
    else:
        # Fallback to index-level breadth
        breadth = load_json("breadth_snapshot.json")
        if not breadth:
            log.warning("No breadth data available, skipping")
            return
        log.info("  Using index-level breadth fallback")

    write_js("market_breadth_snapshot.js", "UI_GLM_MARKET_BREADTH_SNAPSHOT", breadth)


# ============================================================================
# 2b. VNINDEX HEATMAP (stock gainers/losers)
# ============================================================================

def generate_vnindex_heatmap():
    """Tạo vnindex_heatmap_data.js from stock snapshot data."""
    stock_snapshot = load_json("stock_snapshot.json")
    if not stock_snapshot:
        log.warning("No stock_snapshot.json, skipping heatmap")
        return

    gainers = stock_snapshot.get("gainers", [])
    losers = stock_snapshot.get("losers", [])

    if not gainers and not losers:
        log.warning("No gainers/losers data, skipping heatmap")
        return

    output = {
        "date": stock_snapshot.get("asof", ""),
        "gainers": gainers,
        "losers": losers,
        "source": stock_snapshot.get("source", "TCBS"),
    }

    write_js("vnindex_heatmap_data.js", "UI_GLM_VNINDEX_HEATMAP", output)


# ============================================================================
# 3. VNINDEX PRICE 20D
# ============================================================================

def generate_vnindex_price_20d():
    """Tạo vnindex_price_20d.js"""
    index_ohlcv = load_json("index_ohlcv.json")
    if not index_ohlcv:
        log.warning("No index OHLCV, skipping vnindex_price_20d")
        return

    vnindex = index_ohlcv.get("indices", {}).get("vnindex", {})
    bars = vnindex.get("bars", [])[-20:]

    output = {
        "asof": bars[-1]["d"] if bars else "",
        "prices": bars,
    }

    write_js("vnindex_price_20d.js", "UI_GLM_VNINDEX_PRICE_20D", output)


# ============================================================================
# MAIN
# ============================================================================

def main():
    log.info("=" * 60)
    log.info("GENERATING JS DATA FILES...")
    log.info("=" * 60)

    generate_index_ohlcv()
    generate_breadth_snapshot()
    generate_vnindex_price_20d()
    generate_vnindex_heatmap()

    log.info("=" * 60)
    log.info("ALL JS FILES GENERATED!")
    log.info("=" * 60)


if __name__ == "__main__":
    main()
