"""
Tạo JS data files cho dashboard charts.
Chỉ generate các file có data thật từ index OHLCV + breadth.
"""

import json
import sys
import logging
from datetime import datetime
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

sys.path.insert(0, str(Path(__file__).resolve().parent))

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = PROJECT_ROOT / "market_cache"


def load_json(filename):
    path = CACHE_DIR / filename
    if not path.exists():
        log.warning(f"Not found: {path}")
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def write_js(filename, var_name, data):
    """Ghi JS file: window.VAR_NAME = data;"""
    path = PROJECT_ROOT / filename
    content = f"// AUTO-GENERATED by market/generate_market_data_js.py\n"
    content += f"// Generated: {datetime.now().isoformat()}\n"
    content += f"window.{var_name} = {json.dumps(data, ensure_ascii=False)};\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    log.info(f"Written: {path} ({path.stat().st_size:,} bytes)")


# ============================================================================
# 1. INDEX OHLCV (for TradingView charts)
# ============================================================================

def generate_index_ohlcv():
    """Tạo index_ohlcv.js - data OHLCV cho chart."""
    data = load_json("index_ohlcv.json")
    if not data:
        log.warning("No index_ohlcv.json, skipping")
        return

    output = {
        "asof": data.get("asof", ""),
        "updated_at": datetime.now().isoformat(),
        "indices": {},
    }

    for key, index_data in data.get("indices", {}).items():
        output["indices"][key] = {
            "name": index_data["name"],
            "method": "vnstock-VCI",
            "bars": index_data["bars"],
        }

    write_js("index_ohlcv.js", "UI_GLM_INDEX_OHLCV", output)


# ============================================================================
# 2. MARKET BREADTH SNAPSHOT (from index-level data)
# ============================================================================

def generate_breadth_snapshot():
    """Tạo market_breadth_snapshot.js từ breadth_snapshot.json."""
    breadth = load_json("breadth_snapshot.json")
    if not breadth:
        log.warning("No breadth data available, skipping")
        return

    write_js("market_breadth_snapshot.js", "UI_GLM_MARKET_BREADTH_SNAPSHOT", breadth)


# ============================================================================
# 3. VNINDEX PRICE 20D
# ============================================================================

def generate_vnindex_price_20d():
    """Tạo vnindex_price_20d.js"""
    index_ohlcv = load_json("index_ohlcv.json")
    if not index_ohlcv:
        log.warning("No index OHLCV, skipping vnindex_price_20d")
        return

    vnindex = index_ohlcv.get("indices", {}).get("vnindex", {})
    bars = vnindex.get("bars", [])[-20:]

    output = {
        "asof": bars[-1]["d"] if bars else "",
        "prices": bars,
    }

    write_js("vnindex_price_20d.js", "UI_GLM_VNINDEX_PRICE_20D", output)


# ============================================================================
# 4. VNINDEX HEATMAP (from stock_snapshot.json)
# ============================================================================

def generate_vnindex_heatmap():
    """Tạo vnindex_heatmap_data.js - heatmap cổ phiếu tăng/giảm VNINDEX."""
    stock = load_json("stock_snapshot.json")
    if not stock:
        log.warning("No stock_snapshot.json, skipping vnindex heatmap")
        return

    gainers = stock.get("gainers", [])
    losers = stock.get("losers", [])

    if not gainers and not losers:
        log.warning("No gainers/losers data, skipping vnindex heatmap")
        return

    output = {
        "date": stock.get("asof", ""),
        "gainers": gainers,
        "losers": losers,
    }

    write_js("vnindex_heatmap_data.js", "UI_GLM_VNINDEX_HEATMAP", output)


# ============================================================================
# 5. INDEX HEATMAPS (VN30, VN100, VNMIDCAP from top_gainers + top_losers)
# ============================================================================

def generate_index_heatmaps():
    """Tạo index_heatmap_data.js - heatmap cho VN30, VN100, VNMIDCAP."""
    stock = load_json("stock_snapshot.json")
    if not stock:
        log.warning("No stock_snapshot.json, skipping index heatmaps")
        return

    index_stocks = stock.get("index_stocks", {})
    if not index_stocks:
        log.warning("No per-index stock data, skipping index heatmaps")
        return

    output = {
        "asof": stock.get("asof", ""),
        "indices": {},
    }

    for idx_name, idx_data in index_stocks.items():
        stocks = idx_data.get("stocks", [])
        gainers = sorted(
            [s for s in stocks if (s.get("change_pct") or 0) > 0],
            key=lambda x: x.get("change_pct", 0),
            reverse=True,
        )[:30]
        losers = sorted(
            [s for s in stocks if (s.get("change_pct") or 0) < 0],
            key=lambda x: x.get("change_pct", 0),
        )[:30]

        output["indices"][idx_name] = {
            "gainers": gainers,
            "losers": losers,
            "count_pos": len([s for s in stocks if (s.get("change_pct") or 0) > 0]),
            "count_neg": len([s for s in stocks if (s.get("change_pct") or 0) < 0]),
        }

    write_js("index_heatmap_data.js", "UI_GLM_INDEX_HEATMAPS", output)


# ============================================================================
# 6. FOREIGN FLOW DATA
# ============================================================================

def generate_foreign_flow():
    """Tạo foreign_flow_data.js - dữ liệu giao dịch nước ngoài."""
    data = load_json("foreign_data.json")
    if not data:
        log.warning("No foreign_data.json, skipping")
        return

    write_js("foreign_flow_data.js", "UI_GLM_FOREIGN_FLOW", data)


# ============================================================================
# 7. BONDLAB DATA
# ============================================================================

def generate_bondlab():
    """Tạo bondlab_data.js - dữ liệu trái phiếu và liên ngân hàng."""
    data = load_json("bondlab_data.json")
    if not data:
        log.warning("No bondlab_data.json, skipping")
        return

    write_js("bondlab_data.js", "UI_GLM_BONDLAB", data)


# ============================================================================
# 8. RESEARCHLAB DATA
# ============================================================================

def generate_researchlab():
    """Tạo researchlab_data.js - ResearchLab memo data."""
    data = load_json("researchlab_data.json")
    if not data:
        log.warning("No researchlab_data.json, skipping")
        return

    write_js("researchlab_data.js", "UI_GLM_RESEARCHLAB", data)


# ============================================================================
# 9. COMMODITIES DATA
# ============================================================================

def generate_commodities():
    """Tạo commodities_data.js - dữ liệu hàng hoá thế giới."""
    data = load_json("commodities_data.json")
    if not data:
        log.warning("No commodities_data.json, skipping")
        return

    write_js("commodities_data.js", "UI_GLM_COMMODITIES", data)


# ============================================================================
# MAIN
# ============================================================================

def main():
    log.info("=" * 60)
    log.info("GENERATING JS DATA FILES...")
    log.info("=" * 60)

    generate_index_ohlcv()
    generate_breadth_snapshot()
    generate_vnindex_price_20d()
    generate_vnindex_heatmap()
    generate_index_heatmaps()
    generate_foreign_flow()
    generate_bondlab()
    generate_researchlab()
    generate_commodities()

    log.info("=" * 60)
    log.info("ALL JS FILES GENERATED!")
    log.info("=" * 60)


if __name__ == "__main__":
    main()
