#!/usr/bin/env node
/**
 * Build a public/lite dataset from `full_data.js`.
 *
 * Why: GitHub Pages is public. If `full_data.js` contains the full/pro report,
 * anyone can download it even if the UI "hides" sections.
 *
 * This script produces `full_data_public.js` that only contains allowed indices
 * and excludes hidden sections (by title).
 */

const fs = require("fs");
const path = require("path");
const vm = require("vm");

function upperTrim(value) {
  return String(value || "").trim().toUpperCase();
}

function parseCsvEnv(name) {
  const raw = String(process.env[name] || "").trim();
  if (!raw) return null;
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

function loadFullData(fullDataPath) {
  const code = fs.readFileSync(fullDataPath, "utf8");

  // Run in a sandboxed context to materialize FULL_DATA.
  const context = vm.createContext(Object.create(null));
  // Note: `const FULL_DATA = ...` does NOT attach to globalThis by default.
  // Append an assignment so we can read it back from the VM context.
  const glued = `${code}\n;globalThis.FULL_DATA = (typeof FULL_DATA !== 'undefined' ? FULL_DATA : undefined);\n`;
  const script = new vm.Script(glued, { filename: fullDataPath });
  script.runInContext(context, { timeout: 5000 });

  const fullData = context.FULL_DATA;
  if (!fullData || typeof fullData !== "object") {
    throw new Error("FULL_DATA not found after evaluating full_data.js");
  }
  return fullData;
}

function buildPublicData(fullData, allowedIndices, hiddenSections) {
  const out = {};

  for (const [key, value] of Object.entries(fullData)) {
    if (!allowedIndices.has(key)) continue;
    if (!value || typeof value !== "object") continue;

    const sections = Array.isArray(value.sections) ? value.sections : [];
    const publicSections = sections.filter((s) => !hiddenSections.has(upperTrim(s && s.title)));

    out[key] = {
      ...value,
      sections: publicSections,
    };
  }

  return out;
}

function main() {
  const root = path.resolve(__dirname, "..");
  const fullDataPath = process.argv[2] ? path.resolve(process.argv[2]) : path.join(root, "full_data.js");
  const outPath = process.argv[3] ? path.resolve(process.argv[3]) : path.join(root, "full_data_public.js");

  const allowedFromEnv = parseCsvEnv("UI_GLM_PUBLIC_ALLOWED_INDICES");
  const hiddenFromEnv = parseCsvEnv("UI_GLM_PUBLIC_HIDDEN_SECTIONS");

  const allowedIndices = new Set(
    allowedFromEnv || ["overview", "vnindex", "vn30", "vn100", "vnmidcap"]
  );
  const hiddenSections = new Set(
    (hiddenFromEnv || [
      "MÔ HÌNH GIÁ - MÔ HÌNH NẾN",
      "MARKET BREADTH & TÂM LÝ THỊ TRƯỜNG",
      "LỊCH SỬ & XU HƯỚNG BREADTH",
    ]).map(upperTrim)
  );

  const fullData = loadFullData(fullDataPath);
  const publicData = buildPublicData(fullData, allowedIndices, hiddenSections);

  const payload =
    `// AUTO-GENERATED by UI GLM/tools/build_public_data.js\n` +
    `// Source: ${path.basename(fullDataPath)}\n` +
    `const FULL_DATA = ${JSON.stringify(publicData, null, 2)};\n`;

  fs.writeFileSync(outPath, payload, "utf8");
  process.stdout.write(`Wrote ${outPath}\n`);
}

main();
